name: Feature Request
description: Describe the task you will work on
title: "[Task]: "
labels: ["task", "feature"]
projects: ["week-1", "week-2"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Every week you will fill out a task request to describe what you will be working on for the game project until the next week.
  - type: checkboxes
    id: rubric-element
    attributes:
      label: Rubric Criteria
      description: Which part(s) of the rubric are you working on? Check all that apply
      options:
        - label: Gameplay
        - label: Graphics
        - label: Design
        - label: User Experience
        - label: Scripting
        - label: Sound
        - label: Quality
        - label: Process
    validations:
      required: true
  - type: textarea
    id: task-description
    attributes:
      label: Overview
      description: A few sentances describing what you are going to do to move the project up the rubric. Also make sure to attach an image as part of the description
      placeholder: Some many things I want to add to the game!
    validations:
      required: true
  - type: textarea
    id: inspiration
    attributes:
      label: Visual
      description: Please list the game, how it relates and a URL to the game homepage or upload your own image/sketch.
      placeholder: info here
    validations:
      required: true
  - type: textarea
    id: impl-details
    attributes:
      label: What is needed to implement the task?
      description: Please list any needed assets, including scripts, models, images, knowledge
      placeholder: -donut model \nfire particle system \nfire on event script
    validations:
      required: true
  - type: textarea
    id: risk-factor
    attributes:
      label: What is the biggest risk it will not get done?
      description: Be detailed, the more we understand the risks the smaller they are
      placeholder: I do not know how to trigger a particle system from a script
    validations:
      required: true
  - type: textarea
    id: test-case
    attributes:
      label: Test case
      description:  Provide the steps it would take the user to reproduce the behavior
      placeholder: 1) start game \n2) player hits 'W' to run towards donut. \n3) Player intersects with donut. \n4) Donut explodes (particle system trigger_
    validations:
      required: true

